services:
  zotdav:
    container_name: zotdav
    image: zotdav
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - '8843:80'
    volumes:
      - '/mnt/storage/zotdav:/var/www/webdav'
