services:
  zotdav:
    container_name: zotdav
    image: zotdav
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/mnt/storage/zotdav:/var/www/webdav'
      - '/mnt/storage/zotdav/letsencrypt:/etc/letsencrypt'
